title: YuzukiShade
subtitle: YuzukiShade is a GShade Preset
auther: YuzukiTsuru
baseurl: "" 
url: ""

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
repository: YuzukiTsuru/YuzukiShade
repository_index: YuzukiTsuru

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

