name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}/docs:/srv/jekyll -v ${{ github.workspace }}/docs/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.FTP_SERVER_IP }}
        remote-user: ${{ secrets.FTP_SERVER_USERNAME }}
        private-ssh-key: ${{ secrets.FTP_SERVER_PASSWD }}
        destination-path: /www/wwwroot/shade.gloomyghost.com
        source-path: ${{ github.workspace }}/docs/_site/
        rsync-options: --archive --compress --human-readable --progress --delete-after --exclude=. --exclude=.git* --exclude=.git/ --exclude=.well-known/ --exclude=.user.ini --exclude=.gitignore --no-times
        continue-on-error: true
